name: Sync upstream and create PR to main
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Luftalian/pydefect.git

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/kumagai-group/pydefect.git
          git fetch upstream

      - name: Merge upstream/master into local master
        run: |
          git checkout master
          git merge --ff-only upstream/master || echo "No upstream changes to merge."

      - name: Set authenticated remote URL
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Prune origin
        run: git remote prune origin

      - name: Push master to origin
        run: git push origin master

      - name: Check if master and main are different
        id: diffcheck
        run: |
          git fetch origin main
          if git diff --quiet origin/main..origin/master; then
            echo "NO_DIFF=true" >> $GITHUB_ENV
          else
            echo "NO_DIFF=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request from master to main
        if: env.NO_DIFF == 'false'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          base: main
          branch: master
          title: 'Sync master with upstream and propose merge to main'
          body: 'This PR brings in changes from upstream/master via our master branch.'
