name: Update fork
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Luftalian/pydefect
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/kumagai-group/pydefect.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          branch: master