name: Sync upstream and create PR to main

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: sync-upstream
  cancel-in-progress: false

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/kumagai-group/pydefect.git 2>/dev/null || \
          git remote set-url upstream https://github.com/kumagai-group/pydefect.git
          git fetch upstream --tags --prune

      - name: Merge upstream/master into master
        run: |
          git checkout master
          git merge --no-ff --no-edit upstream/master || echo "Nothing to merge."

      - name: Push master (using GITHUB_TOKEN)
        run: |
          git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git master

      - name: Check diff between master and main
        id: diff
        run: |
          git fetch --no-tags origin main
          if git diff --quiet origin/main..HEAD; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create PR master → main
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          base: main
          branch: sync/master-to-main
          title: 'Sync master → main'
          body: 'Syncs fork master (after merging upstream/master) into main.'
          delete-branch: true
